export const shortStackList = [
  {
    id: 1,
    icon: "1",
    title: "Unity",
    desc: "Cross-platform to create one of the extraordinary games while saving time and providing efficient work.",
  },
  {
    id: 2,
    icon: "2",
    title: "Unreal",
    desc: "We are creating iconic games with the help of the most potent 3-D creation tool of game development.",
  },
  {
    id: 3,
    icon: "3",
    title: "React",
    desc: "React is a free and open-source front-end JavaScript library for building user interfaces based on UI components.",
  },
  {
    id: 4,
    icon: "4",
    title: "Node Js",
    desc: "Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on a JavaScript Engine and executes JavaScript code outside a web browser, which was designed to build scalable network applications.",
  },
  {
    id: 5,
    icon: "5",
    title: "Python",
    desc: "Programming language to support a fast and powerful work environment.",
  },
  {
    id: 6,
    icon: "6",
    title: "AWS",
    desc: "Amazon Web Service provides on-demand cloud computing platforms to help reduce costs and innovate faster.",
  },
  {
    id: 7,
    icon: "7",
    title: "Redux",
    desc: "Redux is an open-source JavaScript library for managing and centralizing application state.",
  },
  {
    id: 8,
    icon: "8",
    title: "Photoshop",
    desc: "Graphic editor to enhance pictures and characters to provide outstanding visuals.",
  },
  {
    id: 9,
    icon: "9",
    title: "Illustrator",
    desc: "The graphic editor is used to create vectors, drawings, and sketches.",
  },
  {
    id: 10,
    icon: "10",
    title: "xD",
    desc: "A prototyping tool for UI/UX design and collaborating tool to make wireframes, screen designs, and prototypes.",
  },
  {
    id: 11,
    icon: "11",
    title: "Figma",
    desc: "Design developing tool used by designers and developers to edit and comment on the current project.",
  },
  {
    id: 12,
    icon: "12",
    title: "Maya",
    desc: "Object-oriented programming language for implementing smart contacts on various blockchain platforms",
  },
  {
    id: 13,
    icon: "13",
    title: "Solidity",
    desc: "Object-oriented programming language for implementing smart contacts on various blockchain platforms.",
  },
  {
    id: 14,
    icon: "14",
    title: "digital Ocean",
    desc: "DigitalOcean is a cloud hosting provider that offers cloud computing services and Infrastructure as a Service (IaaS)",
  },
];

export const fullStackList = [
  // {
  //   id: 1,
  //   icon: "1",
  //   title: "Unity",
  //   desc: "Cross-platform to create one of the extraordinary games while saving time and providing efficient work.",
  // },
  // {
  //   id: 2,
  //   icon: "2",
  //   title: "Unreal",
  //   desc: "We are creating iconic games with the help of the most potent 3-D creation tool of game development.",
  // },
  // {
  //   id: 3,
  //   icon: "3",
  //   title: "React",
  //   desc: "React is a free and open-source front-end JavaScript library for building user interfaces based on UI components.",
  // },
  // {
  //   id: 4,
  //   icon: "4",
  //   title: "Node Js",
  //   desc: "Node.js is an open-source, cross-platform, back-end JavaScript runtime environment that runs on a JavaScript Engine and executes JavaScript code outside a web browser, which was designed to build scalable network applications.",
  // },
  // {
  //   id: 5,
  //   icon: "5",
  //   title: "Python",
  //   desc: "Programming language to support a fast and powerful work environment.",
  // },
  // {
  //   id: 6,
  //   icon: "6",
  //   title: "AWS",
  //   desc: "Amazon Web Service provides on-demand cloud computing platforms to help reduce costs and innovate faster.",
  // },
  // {
  //   id: 7,
  //   icon: "7",
  //   title: "Redux",
  //   desc: "Redux is an open-source JavaScript library for managing and centralizing application state.",
  // },
  // {
  //   id: 8,
  //   icon: "8",
  //   title: "Photoshop",
  //   desc: "Graphic editor to enhance pictures and characters to provide outstanding visuals.",
  // },
  // {
  //   id: 9,
  //   icon: "9",
  //   title: "Illustrator",
  //   desc: "The graphic editor is used to create vectors, drawings, and sketches.",
  // },
  // {
  //   id: 10,
  //   icon: "10",
  //   title: "xD",
  //   desc: "A prototyping tool for UI/UX design and collaborating tool to make wireframes, screen designs, and prototypes.",
  // },
  // {
  //   id: 11,
  //   icon: "11",
  //   title: "Figma",
  //   desc: "Design developing tool used by designers and developers to edit and comment on the current project.",
  // },
  // {
  //   id: 12,
  //   icon: "12",
  //   title: "Maya",
  //   desc: "Object-oriented programming language for implementing smart contacts on various blockchain platforms",
  // },
  // {
  //   id: 13,
  //   icon: "13",
  //   title: "Solidity",
  //   desc: "Object-oriented programming language for implementing smart contacts on various blockchain platforms.",
  // },
  // {
  //   id: 14,
  //   icon: "14",
  //   title: "digital Ocean",
  //   desc: "DigitalOcean is a cloud hosting provider that offers cloud computing services and Infrastructure as a Service (IaaS)",
  // },
  {
    id: 15,
    icon: "15",
    title: "after effect",
    desc: "Is a digital visual effect, motion graphics, and compositing application developed by Adobe Systems and used in the post-production process of filmmaking, video games, and television production.",
  },
  {
    id: 16,
    icon: "16",
    title: "Netlify",
    desc: "Netlify is a remote-first cloud computing company that offers a development platform that includes building, deploy, and serverless backend services for web applications and dynamic websites.",
  },
  {
    id: 17,
    icon: "17",
    title: "Zbrush",
    desc: 'Zbrush is a digital sculpting tool that combines 3D/2.5D modeling, texturing, and painting. It uses a proprietary "pixol" technology which stores lighting, color, material, orientation, and depth information for the points making up all objects on the screen.',
  },
  {
    id: 18,
    icon: "18",
    title: "Substance Painter",
    desc: "Substance 3D Painter is a 3D painting software allowing to texture and render 3D meshes.",
  },
  {
    id: 19,
    icon: "19",
    title: "Spine",
    desc: "SPINE is a free, open-source content management system for publishing content on the World Wide Web and intranets.",
  },
  {
    id: 20,
    icon: "20",
    title: "Adobe Premier",
    desc: "Adobe Premiere Pro is a timeline-based and non-linear video editing software application developed by Adobe Inc. and published as part of the Adobe Creative Cloud licensing program.",
  },
  {
    id: 21,
    icon: "21",
    title: "Adobe lightroom",
    desc: "Adobe Lightroom is a creative image organization and image manipulation software developed by Adobe Inc. as part of the Creative Cloud subscription family. ",
  },
  {
    id: 22,
    icon: "22",
    title: "Blender",
    desc: "Blender is a free and open-source 3D computer graphics software tool set used for creating animated films, visual effects, art, 3D-printed models, motion graphics, interactive 3D applications, virtual reality, and, formerly, video games.",
  },
  {
    id: 23,
    icon: "23",
    title: "Substance Designer",
    desc: "Substance 3D Designer is an application intended for creating 2D textures, materials, filters, and 3D models in a node-based interface, with a heavy focus on procedural generation, parametrization, and non-destructive workflows.",
  },
  {
    id: 24,
    icon: "24",
    title: "Adobe InDesign",
    desc: "Adobe InDesign is the industry-leading layout and page design software for print and digital media. Create beautiful graphic designs with typography from the world's top foundries and imagery from Adobe Stock.",
  },
  {
    id: 25,
    icon: "25",
    title: "Constructer 3",
    desc: "Construct 3 is the world's best game-making software. Making games in the browser without coding  or with Javascript.",
  },
  {
    id: 26,
    icon: "26",
    title: "Godot",
    desc: "Godot aims to offer a fully integrated game development environment. It allows developers to create a game, needing no other tools beyond those used for content creation (visual assets, music, etc.).",
  },
  {
    id: 27,
    icon: "27",
    title: "Buildbox",
    desc: "Buildbox is a no-code development platform focused on game creation without programming, coding, or scripting.",
  },
  {
    id: 28,
    icon: "28",
    title: "Play canvas",
    desc: "PlayCanvas is an open-source 3D game engine/interactive 3D application engine alongside a proprietary cloud-hosted creation platform that allows for simultaneous editing from multiple computers via a browser-based interface. ",
  },
  {
    id: 29,
    icon: "29",
    title: "javascript",
    desc: "JavaScript is a scripting language that enables you to create dynamically updating content, control multimedia, animate images, and pretty much everything else.",
  },
  {
    id: 30,
    icon: "30",
    title: "nuxt.js",
    desc: "Nuxt.js is a free and open source JavaScript library based on Vue.js, Node.js, Webpack and Babel.js. Nuxt is inspired by Next.js, which is a framework of similar purpose, based on React.js.",
  },
  {
    id: 31,
    icon: "31",
    title: "Next.js",
    desc: "Next.js is an open-source web development framework created by Vercel enabling React-based web applications with server-side rendering and generating static websites.",
  },
  {
    id: 32,
    icon: "32",
    title: "GraphQL",
    desc: "GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data. ",
  },
  {
    id: 33,
    icon: "33",
    title: "andriod studio",
    desc: "Android Studio provides a unified environment where you can build apps for Android phones, tablets, Android Wear, Android TV, and Android Auto. ",
  },
  {
    id: 34,
    icon: "34",
    title: "flutter",
    desc: "Flutter is Google's portable UI toolkit for crafting beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.",
  },
  {
    id: 35,
    icon: "35",
    title: "Xcode",
    desc: "Xcode includes everything developers need to create great applications for Mac, iPhone, iPad, Apple TV, and Apple Watch.",
  },
  {
    id: 36,
    icon: "36",
    title: "PHP",
    desc: "PHP is an open-source server-side scripting language that many devs use for web development.",
  },
  {
    id: 37,
    icon: "37",
    title: "golang",
    desc: "Go (also called Golang or Go language) is an open-source programming language used for general purposes.",
  },
  {
    id: 38,
    icon: "39",
    title: ".net",
    desc: ". NET is a free, cross-platform, open-source developer platform for building many different types of applications.",
  },
  {
    id: 39,
    icon: "40",
    title: "google Cloud ",
    desc: "Google Cloud provides client libraries that enable you to easily create and manage resources.",
  },
  {
    id: 40,
    icon: "41",
    title: "microsoft azure",
    desc: "Microsoft Azure, often referred to as Azure, is a cloud computing service operated by Microsoft for application management via Microsoft-managed data centers.",
  },
];
