import Head from "next/head";

const FreeSpaceHead = () => {
  return (
    <Head>
      <title>Freespace</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default FreeSpaceHead;
